[tool.poetry]
name = "pre-commit-test"
version = "0.1.0"
description = ""
authors = ["Lorcan Rae <77328552+lorcanrae@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
